/*
 * AgentSight C FFI API
 *
 * Auto-generated by cbindgen — DO NOT EDIT.
 * See docs/design-docs/c-ffi-api.md for usage details.
 */

#ifndef AGENTSIGHT_H
#define AGENTSIGHT_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* Forward declarations for callback parameter types */
typedef struct AgentsightHttpsData AgentsightHttpsData;
typedef struct AgentsightLLMData   AgentsightLLMData;

/* ---- Opaque handles ---- */
typedef struct AgentsightConfigHandle AgentsightConfigHandle;
typedef struct AgentsightHandle       AgentsightHandle;

/* ---- Callback types ---- */
typedef void (*agentsight_https_callback_fn)(const AgentsightHttpsData *data, void *user_data);
typedef void (*agentsight_llm_callback_fn)(const AgentsightLLMData *data, void *user_data);

/* ---- Error handling ---- */
const char *agentsight_last_error(void);

/* ---- Configuration ---- */
AgentsightConfigHandle *agentsight_config_new(void);
void agentsight_config_set_verbose(AgentsightConfigHandle *cfg, int verbose);
void agentsight_config_set_log_path(AgentsightConfigHandle *cfg, const char *path);
void agentsight_config_add_cmdline_rule(AgentsightConfigHandle *cfg, const char *const *rule, const char *agent_name, int allow);
void agentsight_config_add_domain_rule(AgentsightConfigHandle *cfg, const char *rule);
int agentsight_config_load_config(AgentsightConfigHandle *cfg, const char *json_str);
void agentsight_config_free(AgentsightConfigHandle *cfg);

/* ---- Lifecycle ---- */
AgentsightHandle *agentsight_new(AgentsightConfigHandle *cfg);
int agentsight_start(AgentsightHandle *h);
int agentsight_stop(AgentsightHandle *h);
void agentsight_free(AgentsightHandle *h);
const char *agentsight_version(void);

/* ---- Event notification ---- */
int agentsight_get_eventfd(AgentsightHandle *h);

/* ---- Data reading ---- */
#define AGENTSIGHT_READ_BLOCK 1
int agentsight_read(AgentsightHandle *h,
                    agentsight_https_callback_fn http_cb, void *http_ud,
                    agentsight_llm_callback_fn   llm_cb,  void *llm_ud,
                    int flags);

/* ---- Dynamic cgroup filter ---- */
int agentsight_add_traced_cgroup(AgentsightHandle *h, uint64_t cgroup_id);
int agentsight_remove_traced_cgroup(AgentsightHandle *h, uint64_t cgroup_id);

/* ---- Raw event callback type ---- */
typedef struct AgentsightRawEventData AgentsightRawEventData;
typedef void (*agentsight_raw_event_callback_fn)(const AgentsightRawEventData *data, void *user_data);

/* ---- Raw event configuration ---- */
void agentsight_config_set_raw_events(AgentsightConfigHandle *cfg, int enable);
void agentsight_config_set_raw_events_ffi(AgentsightConfigHandle *cfg, int enable);

/* ---- Raw event notification ---- */
int agentsight_get_raw_eventfd(AgentsightHandle *h);

/* ---- Raw event reading ---- */
#define AGENTSIGHT_READ_RAW_BLOCK 1
int agentsight_read_raw(AgentsightHandle *h,
                        agentsight_raw_event_callback_fn raw_cb, void *raw_ud,
                        int flags);


// HTTP layer data — non-LLM HTTPS traffic produces this structure.
typedef struct AgentsightHttpsData {
    int32_t pid;
    char process_name[16];
    uint64_t timestamp_ns;
    uint64_t duration_ns;
    const char *method;
    const char *path;
    uint16_t status_code;
    uint8_t is_sse;
    const char *request_headers;
    uint32_t request_headers_len;
    const char *request_body;
    uint32_t request_body_len;
    const char *response_headers;
    uint32_t response_headers_len;
    const char *response_body;
    uint32_t response_body_len;
} AgentsightHttpsData;

// LLM semantic layer data — only when the HTTP traffic is recognised as
// an LLM API call.
typedef struct AgentsightLLMData {
    const char *response_id;
    const char *conversation_id;
    const char *session_id;
    int32_t pid;
    char process_name[16];
    const char *agent_name;
    uint64_t timestamp_ns;
    uint64_t duration_ns;
    const char *request_url;
    const char *provider;
    const char *model;
    uint16_t status_code;
    uint8_t is_sse;
    const char *finish_reason;
    bool llm_usage;
    uint32_t input_tokens;
    uint32_t output_tokens;
    uint32_t total_tokens;
    uint32_t cache_creation_input_tokens;
    uint32_t cache_read_input_tokens;
    const char *request_messages;
    uint32_t request_messages_len;
    const char *response_messages;
    uint32_t response_messages_len;
} AgentsightLLMData;

// Raw event data passed to the FFI raw event callback.
// All pointers are valid ONLY for the duration of the callback invocation.
typedef struct AgentsightRawEventData {
    uint64_t timestamp_ms;
    const char *source;
    uint32_t pid;
    uint32_t ppid;
    uint32_t tid;
    uint32_t uid;
    char comm[16];
    uint64_t cgroup_id;
    const char *op;
    int32_t ret;
    const char *data_json;
    uint32_t data_json_len;
    uint32_t count;
} AgentsightRawEventData;

#endif  /* AGENTSIGHT_H */
